### ISSUE TITLE
Enhance SVG check during infinite loop

### ISSUE THREAD

**Issue by peter279k** [selective-php/image-type#1]
I found that it has the [infinite loop](https://github.com/selective-php/image-type/blob/master/src/ImageTypeDetector.php#L86) for checking `SVG`.

The infinite loop I think it's not proper and I suggest we should set the `SplFileObject::eof` for the condition.

**Comment by peter279k** [comment]
@odan, I also found that the `SVG` image format is generated by XML document.

Perhaps the four bytes are always `<svg`, and we don't have to use the `while loop`.

**Comment by odan** [comment]
This should be fixed now.

**Comment by peter279k** [comment]
Good. I've looked at the new approach.

Thanks for your concern.
