### ISSUE TITLE
Detect HDR images

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#12]
**HDR**: High Dynamic Range Image

* https://en.wikipedia.org/wiki/High-dynamic-range_imaging
* https://www.cg.tuwien.ac.at/research/publications/2006/Holzer-06-HDR/Holzer-06-HDR-.pdf

### HDR formats

* Cineon and DPX (*.cin,*.dpx): Actually developed for film scans, like RAW uncompressed digital image, therefore very memory intensive
* Portable Float Map (*.pfm,*.pbm): The HDR format with 32 Bit is similar to RAW a simple image, therefore very compatible, but also memory consuming (12 MB for 1 MP)
* Floating Point Tiff (*.tiff): Very flexible, up to 32 bit color depth
* Radiance (*.hdr, *.pic): The first HDR format (1987) has a large dynamic range, but also weaknesses in color resolution; due to its broad user base, it is ideal for exchange
* OpenEXR (*.exr): Very high color resolution, efficient compression, sufficient dynamic range
* Jpeg HDR: Is regarded as tomorrow's format, but is not yet very widespread due to its licensing procedure

**Comment by peter279k** [comment]
I can help this issue and you can assign me to this.

**Comment by peter279k** [comment]
It looks like the HDR image formats have many kinds of things.

Should we split how many detectors for this image detection?

**Comment by peter279k** [comment]
@odan, do you have any idea about this?

**Comment by odan** [comment]
Yes we should create one issue per image format.
