### ISSUE TITLE
Throw exception when it's unrecognized image

### ISSUE THREAD

**Issue by peter279k** [selective-php/image-type#2]
I found that `ImageTypeDetector` class will return null if the image cannot be recognized.

I think we throw exception and message is `Unrecognized image file: /path/to/image/file`.

This can let users know that image is invalid or broken.

And it can also let us know whether image is recognized correctly.

**Comment by odan** [comment]
The method `getImageTypeFromFile` already throws an `ImageTypeException` exception. But I renamed it to `ImageTypeDetectorException`.

**Comment by peter279k** [comment]
@odan, thanks.

I've noticed that it will throw `ImageTypeException` if the `$type` is null in `parseType` method.

Thank you for your explanation.
