### ISSUE TITLE
Detect DNG (Digital Negative)

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#26]
There is new Digital Negative (DNG) format pending:

* https://helpx.adobe.com/photoshop/digital-negative.html
* https://de.wikipedia.org/wiki/Digital_Negative
* 1.4.0.0: https://www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.4.0.0.pdf
* 1.5.0.0: http://wwwimages.adobe.com/www.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.5.0.0.pdf
* http://wwwimages.adobe.com/content/dam/acom/en/products/photoshop/pdfs/DNG_primer_manufacturers.pdf

## Identification

* TIFF tag 50706 ("DNGVersion") (in IFD 0) must be present. 
* This tag should contain the bytes: `1, 2, 0, 0` or  `1, 4, 0, 0` (Version of the DNG specification)
* https://www.awaresystems.be/imaging/tiff/tifftags/dngversion.html
* http://gvsoft.no-ip.org/exif/exif-explanation.html#TiffHeader

**Comment by odan** [comment]
@peter279k Are you interested in creating a PR for this issue?

**Comment by peter279k** [comment]
I can help this issue and you can assign me to this :).
