### ISSUE TITLE
Using static analysis with phpstan for strpos issue

### ISSUE THREAD

**Issue by peter279k** [selective-php/image-type#28]
As title, it seems that we use the latest stable `phpstan` version, but it seems that this doesn't fix the issue currently.

It's related to this `phpstan` [issue](https://github.com/phpstan/phpstan/issues/320).

**Comment by peter279k** [comment]
To avoid this issue, it seems that we use the `strpos($bytes ?: '', 'Hasselblad')......` at this moment.

This code snippets present in the `FR3` and `PEF` image detection.

**Comment by odan** [comment]
Do you see a better solutions / workaround without lowering the phpstan version and level? It thinks we can leave it as it is.

**Comment by peter279k** [comment]
@odan, I figure out we can consider using casting string type to solve this problem.

My approach is as follows:

```php
?php

$files = new SplFileObject('./composer.json', 'r');

strpos((string) $files->fread(4), "php");
```

The original approach is as follows:

```php
?php

$files = new SplFileObject('./composer.json', 'r');

strpos($files->fread(4) ?: "", "php");
```

These two approaches will be passed by `php7.2 vendor/bin/phpstan analyse test.php --level=max -c phpstan.neon --no-progress` command.

I think the casting `string` type is more readable than using `?:` operator.

**Comment by odan** [comment]
> I think the casting string type is more readable than using ?: operator.

Yes, indeed. In this case, casting to string, is fine.

**Comment by peter279k** [comment]
Just notice that these code snippets should change into casting string type style.

![image](https://user-images.githubusercontent.com/9021747/60601496-ce414880-9de4-11e9-90cc-bf8b3cbbe317.png)

I think this work is about the enhancement :).

**Comment by odan** [comment]
Schould be fixed now.
