### ISSUE TITLE
Enhance parseType method

### ISSUE THREAD

**Issue by peter279k** [selective-php/image-type#3]
As title, I found that the `ImageTypeDetector::parseType` method is very complicated for detecting different image formats.

The image formats have different approach about reading byte lengths.

To enhance `parseType` method, my following suggestions are as follows:

- Split different methods from `parseType` methods to detect different images.
- Read constraint bytes can detect every different image formats because we can make sure that the magic bytes should be included in these specific const bytes.
For example, we can read `30` bytes firstly then using `substr` to check the magic bytes are located in current indexes currently.

What do you think about this, @odan?

**Comment by odan** [comment]
I just optimized the `parseType()` method. The code quality increased from D to A :-)

**Comment by peter279k** [comment]
@oda, thanks.

I've looked at the latest commit, and it's better than previous approach :).
