### ISSUE TITLE
PFM - Portable Float Map (HDR)

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#33]
Portable Float Map (.pfm): The HDR format with 32 Bit is similar to RAW a simple image, therefore very compatible, but also memory consuming (12 MB for 1 MP).

**PFM** (Portable Float Map) is an unofficial extension to the pbm image format collection that supports HDR imaging, namely a floating point value per r,g,b [or a single floating point value for grey scale HDR images].

* http://www.pauldebevec.com/Research/HDR/PFM/

**Comment by peter279k** [comment]
I can help this issue.
