### ISSUE TITLE
PBM	- Portable Bit Map (HDR)

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#34]
### PBM	Portable Bit Map (HDR)

* http://paulbourke.net/dataformats/pbmhdr/
* https://en.wikipedia.org/wiki/Netpbm_format

### Identification

The identifier for a PBM HDR image is either "PF" or "Pf" depending on whether it is r,g,b or grey scale.

**Comment by peter279k** [comment]
I can help this issue.
