### ISSUE TITLE
Floating Point TIFF (HDR)

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#35]
### Floating Point Tiff (HDR)

* https://www.cheshireeng.com/HDReye/Downloads.html
* http://chriscox.org/TIFFTN3d1.pdf

**Comment by peter279k** [comment]
I can help this issue.

**Comment by peter279k** [comment]
It seems that this image format is part of the `TIFF`.

It's hard to detect this image because it will return `TIFF` format because it also contains `II` or `MM` magic bytes in first 2 bytes of `TIFF` and `Floating point TIFF`.

**Comment by odan** [comment]
If the TIFF Tag `SampleFormat` contains the value `3` it should be a Floating Point Tiff.

* https://www.awaresystems.be/imaging/tiff/tifftags/sampleformat.html
* https://www.itu.int/itudoc/itu-t/com16/tiff-fx/docs/tiff6.pdf#page=80

This [sample image](https://www.cheshireeng.com/HDReye/files/HDReyeSampleWhiteBalanced.tif) contains 3E or 3D at the same positions. But I'm not sure if this everywhere the case.

![image](https://user-images.githubusercontent.com/781074/60796111-28d3ff00-a16d-11e9-92c0-979c844231b6.png)

But anyway, we can close this issue for now.
