### ISSUE TITLE
Radiance (HDR)

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#36]
### Radiance 

* http://paulbourke.net/dataformats/pic/
* https://en.wikipedia.org/wiki/RGBE_image_format
* http://fileformats.archiveteam.org/wiki/Radiance_HDR

Extenstions: *.hdr, *.pic

## Identification
Files are supposed to begin with an ASCII signature of "#?RADIANCE". However, some apparently begin with "#?RGBE" instead, and some have no signature line at all. Note that some of Radiance's other file formats also use the "#?RADIANCE" signature.

**Comment by peter279k** [comment]
I can help this issue.

**Comment by peter279k** [comment]
About the identification:

```
Files are supposed to begin with an ASCII signature of "#?RADIANCE". However, some apparently begin with "#?RGBE" instead, and some have no signature line at all. Note that some of Radiance's other file formats also use the "#?RADIANCE" signature.
```

It seems that it will have three possible identifications:

- It contains the `"#?RADIANCE"` bytes in the first 10 bytes of image.
- It contains the `#?RGBE"` bytes in the first 6 bytes of image.
- It contains no signature.

@odan, it looks like the image format cannot be detected as `Radiance (HDR)` if it contains no signature.

**Comment by odan** [comment]
> and some have no signature line at all

I think this fact can be ignored. In worst case the detector cannot indentify the Radiance image format. But for all other Radiance files, containing `#?RADIANCE` or `#?RGBE`, the detection should work quite well. I see no problem here.
