### ISSUE TITLE
JPEG HDR

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#38]
## Jpeg HDR

Is regarded as tomorrow's format, but is not yet very widespread due to its licensing procedure.

* https://www.dolby.com/us/en/technologies/jpeg-hdr.html
* https://en.wikipedia.org/wiki/JPEG_XT#JPEG-HDR
* http://fileformats.archiveteam.org/wiki/JPEG-HDR
* http://www.anyhere.com/gward/papers/cic05.pdf

**Comment by peter279k** [comment]
I can help this issue.

**Comment by peter279k** [comment]
@odan, the `JPEG-HDR` is part of the `JPEG`.

Please consider following situations:

- The `JpegDetector` will detect this image format firstly and return the detection result is `JPEG`.
And it will not detect the `JPEG-HDR` correctly.

I think we have two problems:

- We should consider the image format name because this `JPEG-HDR` and `JPEG` have the same image extension name.
- We have to enhance the `JpegDetector` class and avoid `JPEG` formats detection incorrectly.

What do think about this?

**Comment by peter279k** [comment]
I think the third problem will not be the issue because the detection approach is different.

**Comment by odan** [comment]
Yes, JPEG-HDR is quite identical to the classic JPEG. 

But JPEG-HDR is an extension, and uses APP11 segments.

I would suggest we are trying to extract the `ver` (JPEG-HDRVersion) information from the `APP11` JPEG Tag of a JPEG-HDR image. If this tag exists, we asume that it's a JPEG-HDR. I'm aware of the fact, that there are JPEG-HDR file without this tag, but for the most files this should be the case.

![image](https://user-images.githubusercontent.com/781074/60734424-38c2c780-9f50-11e9-989c-a5bf357c501b.png)

* https://sno.phy.queensu.ca/~phil/exiftool/TagNames/JPEG.html#HDR
* https://commons.wikimedia.org/wiki/File:HDRI_Sample_Scene_Window_(JPEG-HDR).jpg 
* http://anyhere.com/gward/papers/cic05.pdf
* https://github.com/exiftool/exiftool/blob/b2961eb457df5ef65dcb7a842ca346bffebcbce7/lib/Image/ExifTool/JPEG.pm#L375

* https://github.com/exiftool/exiftool/blob/668f5020be3f7c1cb73759efe2d14fb30049f414/lib/Image/ExifTool.pm#L6617

* JPEG markers begin with 0xff
* APP11 (JPEG-HDR) marker: `0xeb`
* If the APP11 (JPEG-HDR) marker `0xff0xeb` exists, it should be a JPEG HDR image.

![image](https://user-images.githubusercontent.com/781074/60735455-ad4b3580-9f53-11e9-8903-c9b9397a2027.png)

* Optional: Search for `HDR_RI `.

![image](https://user-images.githubusercontent.com/781074/60735482-d66bc600-9f53-11e9-9d29-5cbf4047a6ca.png)
