### ISSUE TITLE
Detect VIV image file

### ISSUE THREAD

**Issue by peter279k** [selective-php/image-type#73]
The image format reference is available [here](http://fileformats.archiveteam.org/wiki/VIV).

@odan, do we need to implement this image format detection?

It seems that this image format is not common and popular and it's only for the game image format archive.

**Comment by odan** [comment]
VIV looks like a very old and rare file format. I could't even find an example file. I think we can ignore this format, but if you like you can implement it.

**Comment by peter279k** [comment]
@odan, I also agree with your point. And I also don't find any image file.

I think we cannot verify my VIV image detection approach because we are no VIV image files.

I will close this issue because the image format is old and image file we cannot find.
