### ISSUE TITLE
Consider using PSR-12 coding style

### ISSUE THREAD

**Issue by peter279k** [selective-php/image-type#74]
According to this [doc reference](https://www.php-fig.org/psr/psr-2/), It seems that the `PSR-2` coding style is marked as deprecated by `PHP-FIG` organization.

Should we transfer to `PSR-12` coding style?

**Comment by odan** [comment]
Yes, of course! As soon as PHP-CS is ready for PSR-12. (Afaik, most of the code base is already PSR-12 compatible)

**Comment by peter279k** [comment]
It seems that this setting has been defined on https://github.com/selective-php/image-type/blob/master/phpcs.xml#L13.

And this issue I think is going to be closed.
