### ISSUE TITLE
Detect CR3 RAW images

### ISSUE THREAD

**Issue by odan** [selective-php/image-type#8]
A camera raw image file contains minimally processed data from the image sensor of either a digital camera, a motion picture film scanner, or other image scanner.

Specification:
* https://en.wikipedia.org/wiki/Raw_image_format
* https://github.com/lclevy/canon_cr3

**Comment by peter279k** [comment]
After looking at the contents of Canon `CR3` raw image format, it seems that the magic bytes are `ftypcrx`.

We can use these image bytes to identify this raw image format.

**Comment by peter279k** [comment]
@odan, I've noticed that it has other raw image formats.

They're mentioned in this [wiki introduction](https://en.wikipedia.org/wiki/Raw_image_format).

Do we need to implement these image formats detection?

Or we can consider picking up them, not implement all of image formats detection?

**Comment by odan** [comment]
Good question.

> There are dozens, if not hundreds, of raw formats in use by different models of digital equipment (like cameras or film scanners)

TIFF based RAW formats:

* IIQ (Phase One)
* 3FR (Hasselblad) :heavy_check_mark:
* DCR, K25, KDC (Kodak)
* CRW
* CR2  :heavy_check_mark:
* ERF (Epson)
* MEF (Mamiya)
* MOS (Leaf)
* NEF (Nikon)
* ORF (Olympus)
* PEF (Pentax) :heavy_check_mark:
* RW2 (Panasonic) :heavy_check_mark:
* ARW, SRF, SR2 (Sony)

Oh yeah, there are really quite a lot RAW formats :-)

> The ISO standard raw image format is ISO 12234-2, better known as TIFF/EP.

The most of them are based on the TIFF file format. These files may deviate from the TIFF standard in a number of ways, including the use of a non-standard file header, the inclusion of additional image tags and the encryption of some of the tagged data.

Then we have **container** based RAW formats:
* CR3 (Canon)  :heavy_check_mark:

And there is new Digital Negative (DNG) format pending:
* DNG (Leica) (https://helpx.adobe.com/photoshop/digital-negative.html)

I think we should focus on the most used RAW formats firsts.

For example the older RAW format like CR2 (TIFF based):

* http://lclevy.free.fr/cr2/ 
* https://github.com/lclevy/libcraw2/blob/master/docs/cr2_poster.pdf
* https://github.com/lclevy/libcraw2

**Comment by peter279k** [comment]
@odan, thank you for your reply. Ok. We can focus on old RAW image formats firstly,

Could you have the individual issue about raw image format detection?

So that we can track the progress of RAW image formats detection one by one :).

**Comment by odan** [comment]
I just created new issues for the other RAW formats.
